name: "Terraform CI/CD - Produzione"

on:
  push:
    branches:
      - main 

jobs:
  terraform:
    name: "Terraform Deploy Prod"
    runs-on: ubuntu-latest
    
    # NOVITÀ: Diciamo alla pipeline di eseguire i comandi in questa cartella!
    defaults:
      run:
        working-directory: environments/prod
        
    # AGGIUNTA: Definiamo le variabili d'ambiente per Terraform a livello di job
    env:
      # Sostituisci "telegram_token_value" se l'hai chiamata "telegram_token"
      TF_VAR_telegram_token_value: ${{ secrets.TELEGRAM_TOKEN }}
      TF_VAR_telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Autenticazione GCP (Prod)
        uses: google-github-actions/auth@v2
        with:
          # Assicurati che questo segreto abbia i permessi sul progetto di Produzione
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve